name: deploy maven package to snapshots
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  maven-deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - run: JAVA_HOME=$JAVA_HOME mvn deploy --settings settings.xml -P github-snapshot -Dbranch=${BRANCH_NAME}
        env:
          maven_username: ${{secrets.MAVEN_USERNAME}}
          maven_password: ${{secrets.MAVEN_PASSWORD}}